# Generated by Django 4.2.5 on 2024-04-19 19:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время начала тренировки')),
                ('count_approaches', models.IntegerField(blank=True, null=True, verbose_name='Количество подходов')),
                ('count_repetitions', models.IntegerField(blank=True, null=True, verbose_name='Количество повторений')),
                ('title_exercise', models.TextField(blank=True, null=True, verbose_name='Название тренировки')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workoutsession', to=settings.AUTH_USER_MODEL, verbose_name='Тренировка пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Название видео', models.CharField(max_length=100)),
                ('description', models.TextField(verbose_name='Описание видео')),
                ('duration', models.FloatField(verbose_name='Продолжительность видео в минутах')),
                ('file_path', models.FileField(upload_to=pathlib.PureWindowsPath('D:/PythonDev/begin_with_yourself_bot_1/django_bot/backend_media'), verbose_name='Путь к файлу с видео')),
                ('difficulty', models.CharField(choices=[('beginner', 'Начинающий'), ('middle', 'Средний'), ('pro', 'Продвинутый')], default='Начинающий', max_length=32, verbose_name='Сложность')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='base.category', verbose_name='категория тренировки')),
            ],
        ),
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_down', models.DateTimeField(blank=True, null=True, verbose_name='Отход к сну')),
                ('time_up', models.DateTimeField(blank=True, null=True, verbose_name='Подъем')),
                ('time_sleep', models.TextField(blank=True, null=True, verbose_name='Время сна')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.FloatField(validators=[django.core.validators.MinValueValidator(1000.0), django.core.validators.MaxValueValidator(4000.0)], verbose_name='Калории')),
                ('protein', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1000.0)], verbose_name='Белок')),
                ('fats', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1000.0)], verbose_name='Жир')),
                ('carbohydrates', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1000.0)], verbose_name='Углевод')),
                ('date_record', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи.')),
                ('user_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='nutrients', to=settings.AUTH_USER_MODEL, verbose_name='ИД Пользователя')),
            ],
            options={
                'verbose_name': 'Питательные вещества продукта',
                'verbose_name_plural': 'Питательные вещества',
                'ordering': ['user_id'],
            },
        ),
    ]
