# Generated by Django 4.2.5 on 2024-04-21 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nutrients',
            options={'ordering': ['chat'], 'verbose_name': 'Питательные вещества продукта', 'verbose_name_plural': 'Питательные вещества'},
        ),
        migrations.RemoveField(
            model_name='nutrients',
            name='user_id',
        ),
        migrations.AddField(
            model_name='nutrients',
            name='chat',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Идентификатор чата в телеграмме'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainingvideo',
            name='file_path',
            field=models.FileField(upload_to='media_files/', verbose_name='Путь к файлу с видео'),
        ),
    ]
