version: '3.3'

volumes:
  pg_data:
  static:
  media_volume:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  django_bot:
    build: 
      context: ../django_bot/
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - static:/backend_static
      - media_volume:/media_files
  bot:
    build:
      context: ../Bot
      dockerfile: Dockerfile
    env_file: .env
  gateway:
    build:
      context: ../nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8000:80"
    volumes:
      - static:/staticfiles/
      - media_volume:/media_files
