# Generated by Django 4.2.5 on 2024-04-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='chat',
            field=models.BigIntegerField(unique=True, verbose_name='Идентификатор чата в телеграмме'),
        ),
    ]
